version: "3"

services:
  mtproxy:
    build: ./
    image: serbgost/mtproxy:latest
    restart: always
    volumes:
      # config folder must contain two files: 'proxy-secret' and 'proxy-multi.conf'
      # for details see https://github.com/TelegramMessenger/MTProxy#running
      - ./shared-config:/mtproxy/config

    env_file:
      - ./config/conf.env

    ports:
      - 8443:443
      - 8888:8888